### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by ComputersAndTech** [rachelproject/eos-justice#10]
Create bookmarks in chrome that will be available on any account created (and enable bookmark bar by default).

Bookmarks that need to be added are 

file:///var/opt/rachelusb_32JU/RACHEL/index.html
file:///var/opt/rachelusb_32JU/RACHEL/modules/saylor/content/www.saylor.org/books.html
file:///var/opt/rachelusb_32JU/RACHEL/modules/en-rachelcourses/index.html
file:///var/opt/rachelusb_32JU/RACHEL/modules/en-GCF2015/index.html
file:///var/opt/rachelusb_32JU/RACHEL/modules/en-oya-static/index.html

**Comment by quarckster** [comment]
I don't think it's possible.

**Comment by ComputersAndTech** [comment]
If that's not possible what about putting a shortcut to the html pages listed on the desktop?

**Comment by j-schwartz** [comment]
@quarckster -- is the shortcut automation possible?

**Comment by quarckster** [comment]
@j-schwartz it seems it's not so easy. EOS doesn't allow to add the shortcuts with urls starting with file.
