### ISSUE TITLE
Offline Install of Chrome

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/eos-justice#11]
Hi @quarckster  -- is it possible for us to host a separate copy of chrome on our local servers so we don't need to ping the internet to install it?  We're trying to prepare ~100 machines without internet around, but we will need chrome (the other apps to install are not as important)

**Comment by quarckster** [comment]
After investigating Chrome installation process in EndlessOS I found that flatpak bundle is just a wrapper which downloads a usual deb package and installs it. So it will be downloaded in any case. There is Chromium already preinstalled if you need a browser from the start.

**Comment by j-schwartz** [comment]
Thanks @quarckster -- I know this is an unusual ask, but is there a way to host the chrome deb package on a separate local (offline) server and use that to install Chrome on Endless?  For context, we are bringing 100 laptops into a prison.  Once the laptop hardware is there, we would like to use the USB to install full Endless, and then your script to configure the devices.  Our agreement with the prison stipulates that the laptops will **never** touch the internet.  The laptops can however be connected to a LAN, which on the LAN we plan to host a content server (also offline, but preloaded with everything we need).  We will point the laptops at the content server to get all the RACHEL content.  My concern is just the basic, can I host the Chrome debian on our content server, and if so, will I be able to install in on Endless.  I know little about this type of processes and even less about flatpaks.

**Comment by j-schwartz** [comment]
outdated
