### ISSUE TITLE
Not downloading from local rsync server

### ISSUE THREAD

**Issue by ComputersAndTech** [rachelproject/eos-justice#4]
I've gotten the repository downloaded apart from the French and Portuguese languages, but from what I can tell the script downloads from the internet regardless of if you specify an rsync server.

The command I've been running to download from my rsync server is

wget -nv -O - https://raw.githubusercontent.com/rachelproject/eos-justice/master/eos.sh | sudo bash -s --192.168.1.35

Where 192.168.1.35 is the server I set up.

I tested that the rsync server exists and is working on both the vm I'm running it on, and the laptop I'm trying to update by running the command

rsync -azn --info=progress2 rsync://192.168.1.35 /opt

and it outputs

rachelmods           RACHEL modules

on both computers.

However when I run the script it doesn't appear to be downloading from the rsync server (I'm running a bandwidth monitor on the server to verify), and when I look at the script, it looks like it grabs one thing from the local rsync server, and the rest from the endlessos server. Am I doing something wrong or does the script need to be adjusted?

**Comment by j-schwartz** [comment]
Hi kevin - will defer to Dimitry but I'm reading this again.  There isn't
any overlap in content between the Endless servers and the local server you
set up.  Basically, I think it is doing what it is supposed to.

There is overlap between world possible's RACHEL server and your local
repository, but we do not duplicate anything that endless offers.  If
content is coming from Endless in particular, that is the only source of
content.

**Comment by ComputersAndTech** [comment]
If that's the case than I need to set up a repository for the endlessos stuff, even if it has to be updated regularly, because my internet will have a hard time handling a large scale of laptops as I have a 1tb cap and the connection to the offsite server during the day is sometimes sub 500kbps.

**Comment by quarckster** [comment]
According this line https://github.com/rachelproject/eos-justice/blob/master/eos.sh#L111 rachel modules always downloaded from dev.worldpossible.org. @j-schwartz do we need to change it?

**Comment by ComputersAndTech** [comment]
I need that, as well as the kalite stuff downloadable by a custom rsync url.

I synced an rsync server with the worldpossible repository so that I have a local copy to improve the speed of updating the laptops and pushing them out.

If I'm the only one that needs this a switch could be added into the command to enable that functionality for me.

**Comment by j-schwartz** [comment]
If we can set it up to download locally by typing in an up address that'd
be great. Computers in tech is doing the actually building of machines so
I'll defer to him. Please still use upwork for us.
