### ISSUE TITLE
Case sensitive typo

### ISSUE THREAD

**Issue by ComputersAndTech** [rachelproject/eos-justice#5]
On line 23 en-phet needs to be changed to en-PhEt as it keeps throwing errors when trying to rsync, because the case is different it says the directory does not exist. I can change it on my end but every time I sync it's going to have to be changed again.

**Comment by j-schwartz** [comment]
thanks, I just made the change.

**Comment by j-schwartz** [comment]
changed

**Comment by ComputersAndTech** [comment]
I typoed the typo, it's "en-PhET"

**Comment by j-schwartz** [comment]
boom, done! PhET

**Comment by quarckster** [comment]
@j-schwartz, just fyi, the script has its own list of rachel modules, it doesn't read `eos-en-modules` file. I've already fixed case in the code.

**Comment by j-schwartz** [comment]
Oh, thanks Dmirty! Do we need that eos-en-modules file for anything?

**Comment by quarckster** [comment]
No, it's not used at all.
