### ISSUE TITLE
Other apps that need to be removed.

### ISSUE THREAD

**Issue by ComputersAndTech** [rachelproject/eos-justice#6]
These apps need to be removed from endlessos for the justice computers to prevent access to certain things.

Video Net
Weather
Cheese
Brasero
Evolution
Archive Manager
Remote Desktop

Another one not listed in the App store but shows up on the task bar is Facebook.

**Comment by quarckster** [comment]
@j-schwartz please approve

**Comment by j-schwartz** [comment]
approved - thanks Dmitry

**Comment by quarckster** [comment]
Added Video Net and Weather to remove list in 023b4b5. Other applications cannot be removed using standard tools.
