### ISSUE TITLE
New Endless Breaking Script

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/eos-justice#7]
Hi Dmitry -- would it be possible to re-write application locations or commands to match the latest version of Endless, I currently get the following when running the script:

> jeremy@endless:~$ wget -nv -O - https://raw.githubusercontent.com/rachelproject/eos-justice/master/eos.sh | sudo bash -s --192.168.1.75
> 
> We trust you have received the usual lecture from the local System
> Administrator. It usually boils down to these three things:
> 
>     #1) Respect the privacy of others.
>     #2) Think before you type.
>     #3) With great power comes great responsibility.
> 
> 2017-03-16 10:07:18 URL:https://raw.githubusercontent.com/rachelproject/eos-justice/master/eos.sh [5017/5017] -> "-" [1]
> [sudo] password for jeremy: 
> bash: --: invalid option
> Usage:	bash [GNU long option] [option] ...
> 	bash [GNU long option] [option] script-file ...
> GNU long options:
> 	--debug
> 	--debugger
> 	--dump-po-strings
> 	--dump-strings
> 	--help
> 	--init-file
> 	--login
> 	--noediting
> 	--noprofile
> 	--norc
> 	--posix
> 	--rcfile
> 	--restricted
> 	--verbose
> 	--version
> Shell options:
> 	-ilrsD or -c command or -O shopt_option		(invocation only)
> 	-abefhkmnptuvxBCHP or -o option
> jeremy@endless:~$ wget -nv -O - https://raw.githubusercontent.com/rachelproject/eos-justice/master/eos.sh | sudo bash -s -- 192.168.1.75/rachelmods/
> 2017-03-16 10:07:32 URL:https://raw.githubusercontent.com/rachelproject/eos-justice/master/eos.sh [5017/5017] -> "-" [1]
> Starting to delete applications
> bash: line 45: Uninstalling: command not found
> Deleting org.kde.Knavalbattle failed
> bash: line 45: Uninstalling: command not found
> Deleting net.sourceforge.Atanks failed
> bash: line 45: Uninstalling: command not found
> Deleting net.sourceforge.Btanks failed
> bash: line 45: Uninstalling: command not found
> Deleting com.endlessm.celebrities.en failed
> bash: line 45: Uninstalling: command not found
> Deleting com.endlessm.cooking.en failed
> bash: line 45: Uninstalling: command not found
> Deleting com.endlessm.encyclopedia.en failed
> bash: line 45: Uninstalling: command not found
> Deleting org.kde.Killbots failed
> bash: line 45: Uninstalling: command not found
> Deleting net.olofson.Kobodeluxe failed
> bash: line 45: Uninstalling: command not found
> Deleting org.marsshooter.Marsshooter failed
> bash: line 45: Uninstalling: command not found
> Deleting com.endlessm.maternity.en failed
> error: org.megaglest.Megaglest master not installed
> Deleting org.megaglest.Megaglest failed
> bash: line 45: Uninstalling: command not found
> Deleting org.openarena.Openarena failed
> bash: line 45: Uninstalling: command not found
> Deleting net.sourceforge.Warmux failed
> bash: line 45: Uninstalling: command not found
> Deleting net.wz2100.Warzone2100 failed
> bash: line 45: Uninstalling: command not found
> Deleting org.wesnoth.Wesnoth failed
> bash: line 45: Uninstalling: command not found
> Deleting com.endlessm.videonet failed
> bash: line 45: Uninstalling: command not found
> Deleting com.endlessm.weather failed
> Applications deleting finished
> Starting to install applications
> error: The Application com.google.Chrome/x86_64/eos3.0 requires the runtime com.endlessm.Platform/x86_64/eos3.0 which is not installed
> bash: line 57: Required: command not found
> com.google.Chrome installation failed
>

**Comment by quarckster** [comment]
You provided wrong argument and missed space after `--`

**Comment by j-schwartz** [comment]
@quarckster I think I'm still having the same issue with corrected syntax:

jeremy@endless:~$ wget -nv -O - https://raw.githubusercontent.com/rachelproject/eos-justice/master/eos.sh | sudo bash -s 
2017-03-30 09:04:19 URL:https://raw.githubusercontent.com/rachelproject/eos-justice/master/eos.sh [5017/5017] -> "-" [1]
[sudo] password for jeremy: 
Starting to delete applications
error: org.kde.Knavalbattle master not installed
Deleting org.kde.Knavalbattle failed
error: net.sourceforge.Atanks master not installed
Deleting net.sourceforge.Atanks failed
error: net.sourceforge.Btanks master not installed
Deleting net.sourceforge.Btanks failed
error: com.endlessm.celebrities.en master not installed
Deleting com.endlessm.celebrities.en failed
error: com.endlessm.cooking.en master not installed
Deleting com.endlessm.cooking.en failed

**Comment by quarckster** [comment]
In Endless OS 3.1.3 there are no these packages preinstalled, so they can't be deleted

**Comment by j-schwartz** [comment]
Hi @quarckster -- These items do come pre-installed, I just booted up a new clean Endless 3.1.3 English Full and can confirm packages such as celebrities and wikipedia are on the device.

It also appears as though despite this verbage: 

> [sudo] password for jeremy: 2017-03-31 12:01:18 URL:https://raw.githubusercontent.com/rachelproject/eos-justice/master/eos.sh [5017/5017] -> "-" [1]
> 
> Starting to delete applications
> bash: line 45: Uninstalling: command not found
> Deleting org.kde.Knavalbattle failed
> bash: line 45: Uninstalling: command not found
> Deleting net.sourceforge.Atanks failed
> bash: line 45: Uninstalling: command not found
> Deleting net.sourceforge.Btanks failed
> bash: line 45: Uninstalling: command not found
> Deleting com.endlessm.celebrities.en failed
> bash: line 45: Uninstalling: command not found

They are getting uninstalled.  This is further confusing though, because while the icons for Encyclopedia are removed from the device, the App Center continues to say these items are "installed" but when actually attempting to "launch" them, the applications do not launch.  

Do you think this is something I should try addressing with Endless or that there might be something on our end causing this confusion?

**Comment by quarckster** [comment]
I got it, I have tried to run the script only basic EndlessOS version.

**Comment by j-schwartz** [comment]
I also think the newest endless 3.1.3 is failing to install KALite with the script:

> > error: The Application com.google.Chrome/x86_64/eos3.0 requires the runtime com.endlessm.Platform/x86_64/eos3.0 which is not installed
> bash: line 57: Required: command not found
> com.google.Chrome installation failed
> error: The Application org.learningequality.KALite/x86_64/eos3.0 requires the runtime com.endlessm.Platform/x86_64/eos3.0 which is not installed
> bash: line 57: Required: command not found
> org.learningequality.KALite installation failed
> Applications installation finished
>

**Comment by quarckster** [comment]
Fixed in 3331468
