### ISSUE TITLE
Programs to add to the install list.

### ISSUE THREAD

**Issue by ComputersAndTech** [rachelproject/eos-justice#9]
Android Studio
Arduino IDE
Builder
Code Blocks
Processing
Snap4Arduino

**Comment by j-schwartz** [comment]
@quarckster can these be automated for download?

**Comment by quarckster** [comment]
if these programs are in the eos repo it can be automated.

**Comment by j-schwartz** [comment]
They should be, if you can add to the script it'd be much appreciated.  We're giving @ComputersAndTech freedom to design the system and will continue to cover any costs you have through elance.  Just want to make sure whatever he designs can be easily replicated by your script.
